######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
gems: ["jekyll-paginate", "wdm"]
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
  
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     /articles/:year/:month/:day/:title
paginate_path: /page:num
timezone:      null


#Site config
title: 记忆碎片
description: 书写是为了总结，总结是为了前进！
keywords: github, jekyll, java
url: /blog
feed: /atom.xml
favicon: http://www.iclojure.com/favicon.ico

#Nav config
nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html
  - text: 联系我
    url: navigations/contact.html
  - text: 友情链接
    url: navigations/links.html

#Author config
author:
    name: whg
    email: wanghg_java@163.com
    imageLink: http://www.iclojure.com/avatars.jpg
    simpleIntro: 我是「 whg」
    detailIntro:
      <p>记忆碎片——书写是为了总结，总结是为了前进！</p>
      <p>QQ：<a href='tencent://message/?uin=2697246754'>2697246754</a></p>
      <p>豆瓣：<a href='http://www.douban.com/people/iclojure/'>whg</a></p>
      <p>GitHub：<a href='https://github.com/whg333'>whg333</a></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: https://github.com/whg333
  - class: icon-twitter
    url: http://twitter.com
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 掌心
      url: http://www.zhanxin.info
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    - text: canvas-nest.js
      url: https://github.com/aTool-org/canvas-nest.js/blob/master/README-zh.md
    - text: 人体时钟hone hone clock
      url: http://ziren.org/tools/hone-hone-clock.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#comment config
disqus:
  config: false
  id: whg
  
duoshuo:
  config: true
  id: iclojure

#################################### global configure #######################################
username: whg333
baseurl: /blog

title: 记忆碎片
description: 书写是为了总结，总结是为了前进！
theme: kunka
disqusname: whg

#custom variables
domainname: www.iclojure.com

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
